source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'MCUIKitDemo' do
  pod 'MCBase/All', git: 'https://github.com/poholo/MCBase'
  pod 'MCStyle'
  pod 'MJRefresh'
  pod 'Masonry'
  pod 'MBProgressHUD'
  pod 'HMSegmentedControl'
  pod 'SDWebImage'
  pod 'MMPopupView'
end
